services:
    app:
      image: golang:1.21.3-alpine3.17
      ports:
        - '1323:1323'
      working_dir: /workspace
      volumes:
        - type: bind
          source: ./app
          target: /workspace
      command: go run main.go

    prometheus:
      image: prom/prometheus
      ports:
        - '9090:9090'
      volumes:
        - type: bind
          source: ./prometheus
          target: /etc/prometheus
      command: --config.file=/etc/prometheus/prometheus.yml
    
    grafana:
      image: grafana/grafana
      ports:
        - '3000:3000'
